# Generated by Django 6.0.7 on 2026-08-04 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cost_points', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.CreateModel(
            name='TierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('min_points', models.PositiveIntegerField()),
                ('max_points', models.PositiveIntegerField(blank=True, help_text='Vazio = sem teto (tier máximo).', null=True)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('free_shipping', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição/progressão (0 = mais baixo).')),
            ],
            options={
                'verbose_name': 'Regra de Tier',
                'verbose_name_plural': 'Régua de Tiers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positivo = crédito, negativo = débito (ex: resgate).')),
                ('reason', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('PURCHASE', 'Compra na loja'), ('EVENT_CHECKIN', 'Check-in em evento'), ('REDEMPTION', 'Resgate de recompensa'), ('MANUAL', 'Ajuste manual'), ('EXTERNAL_DISCORD', 'Discord'), ('EXTERNAL_TWITCH', 'Twitch'), ('EXTERNAL_SHOPIFY', 'Shopify')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação de Pontos',
                'verbose_name_plural': 'Extrato de Pontos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.rewarditem')),
            ],
            options={
                'verbose_name': 'Resgate',
                'verbose_name_plural': 'Resgates',
                'ordering': ['-created_at'],
            },
        ),
    ]
