# Generated by Django 6.0.7 on 2026-08-04 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True)),
                ('total_points', models.IntegerField(default=0, help_text='Acumulado histórico, nunca decresce.')),
                ('current_balance', models.IntegerField(default=0, help_text='Saldo disponível para resgates/trocas.')),
                ('tier', models.CharField(choices=[('INICIANTE', 'B10 Iniciante'), ('RITMISTA', 'Ritmista'), ('PUXADOR', 'Puxador do Caos'), ('LENDA', 'Lenda B10')], default='INICIANTE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Torcedor',
                'verbose_name_plural': 'Perfis dos Torcedores',
            },
        ),
    ]
